#!/bin/sh
#if [ ${USER} == "root" ]
#then
# Change file owner
# 1. libraries
#        chown root:root /usr/lib/libcups.so        
#        chown root:root /usr/lib/libcupsmime.so       
#        chown root:root /usr/lib/libcupsppdc.so
#        chown root:root /usr/lib/libcupsimage.so 
#        chown root:root /usr/lib/libcupsdriver.so 
# 2. executables
# 3. configurations
	#chown root:root /usr/lib/pkgconfig/cups.pc
#	chown root:root /usr/include/cups/cups.h 
#	chown root:root /usr/include/cups/dir.h 
#	chown root:root	/usr/include/cups/driver.h
#	chown root:root /usr/include/cups/file.h
#	chown root:root /usr/include/cups/http.h
#	chown root:root /usr/include/cups/adminutil.h 
#	chown root:root /usr/include/cups/array.h  
#	chown root:root /usr/include/cups/backend.h  
#	chown root:root /usr/include/cups/mime.h 
#	chown root:root	/usr/include/cups/ppd.h 
#	chown root:root /usr/include/cups/ppdc.h 
#	chown root:root /usr/include/cups/image.h
#	chown root:root /usr/include/cups/ipp.h
#fi

#if [ ${USER} == "root" ]
#then
# Change file owner
# 1. libraries
#        chown root:root /usr/lib/libavahi-client.so.3        
# 2. executables
# 3. configurations
#	chown root:root /usr/lib/pkgconfig/avahi-client.pc
#	chown root:root /usr/include/avahi-client/client.h  
#	chown root:root /usr/include/avahi-client/lookup.h
#	chown root:root	/usr/include/avahi-client/publish.h
#fi

#if [ ${USER} == "root" ]
#then
# Change file owner
# 1. libraries       
#        chown root:root /usr/lib/libavahi-common.so.3      
# 2. executables
# 3. configurations
	#chown root:root /usr/lib/pkgconfig/avahi-common.pc.pc
#	chown root:root /usr/include/avahi-common/address.h   
#	chown root:root /usr/include/avahi-common/alternative.h
#	chown root:root	/usr/include/avahi-common/cdecl.h 	
#	chown root:root /usr/include/avahi-common/defs.h  
#	chown root:root /usr/include/avahi-common/domain.h
#	chown root:root	/usr/include/avahi-common/error.h  
#	chown root:root /usr/include/avahi-common/gccmacro.h   
#	chown root:root /usr/include/avahi-common/llist.h
#	chown root:root	/usr/include/avahi-common/malloc.h  
#	chown root:root /usr/include/avahi-common/rlist.h  
#	chown root:root /usr/include/avahi-common/simple-watch.h
#	chown root:root	/usr/include/avahi-common/strlst.h  
#	chown root:root /usr/include/avahi-common/thread-watch.h   
#	chown root:root /usr/include/avahi-common/timeval.h
#	chown root:root	/usr/include/avahi-common/watch.h  
#fi

#if [ ${USER} == "root" ]
#then
# Change file owner
# 1. libraries    
#        chown root:root /usr/lib/libavahi-core.so.5
# 2. executables
# 3. configurations
#	chown root:root /usr/lib/pkgconfig/avahi-core.pc
#fi

# Change file permissions
# 1. libraries
#chmod 644 /usr/lib/libprint-service.so
# 2. executables
# 3. configurations
chmod 644 /usr/lib/pkgconfig/print-service.pc
chmod 644 /usr/include/print-service/pt_api.h
